# Generated by Django 2.1.3 on 2018-12-06 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('myprojapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('user', models.OneToOneField(on_delete='CASCADE', primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=models.CharField(max_length=500),
        ),
    ]
