# Generated by Django 2.1.3 on 2018-12-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojapp', '0003_auto_20181206_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userschedule',
            name='user',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='UserSchedule',
        ),
    ]
